language: node_js
node_js:
- "8.11"

branches:
  only:
  - master

addons:
  chrome: stable

before_script:
- yarn global add @angular/cli # cette commannde permet de mettre en cache pour ne pas avoir a reinstaller a chaque fois

cache:
  yarn: true
  directories: #  dans ce repertoire pour le cache
  - node_modules

script:
- ng build --prod


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: ./dist/
  on:
